server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称,改域名修改host实现
  client:
    #是否将自己注册进Eureka
    register-with-eureka: false
    #是否从Eureka中抓取已有注册信息
    fetch-registry: false
    service-url:
      #server端地址
      #集群模式，相互注册
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #是否开启自我保护
    enable-self-preservation: false
    #server清除无效服务的周期，此处每2s清理一次无效服务
    eviction-interval-timer-in-ms: 2000
